name: Deploy to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run predeploy
        env:
          NODE_ENV: production
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
