name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Chromium Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libxkbcommon-x11-0 \
            libpangocairo-1.0-0 \
            libgdk-pixbuf2.0-0 \
            libasound2 \
            libnspr4 \
            fonts-liberation \
            xdg-utils

      - name: Install Dependencies
        run: npm ci

      - name: Check Puppeteer Installation
        run: |
          node -e "console.log(require('puppeteer').executablePath())"

      - name: Build and Deploy
        env:
          NODE_ENV: production
          REACT_APP_GA_TRACKING_ID: UA-68649021-1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/DJustice23/personal-site.git
          npm run predeploy
          npm run deploy
